### ISSUE TITLE
How to access image sequences and reproduce GPT-4V results?

### ISSUE THREAD

**Issue by leixy20** [si0wang/Mementos#1]
Thanks for your great work!
I have downloaded the data and i noticed all the image sequences are combined images. In your paper, you mentioned that you tested GPT-4V using separate images sequentially, so i wonder how to get the image sequences and reproduce the GPT-4V results? (Cropping the combined image is feasible but maybe not elegant ...)
Thanks for your help!

**Comment by Mementos-bench** [comment]
Hi, you can download the zip file whose name starts with single_, which contains sequential single images.

**Comment by si0wang** [comment]
Hi, you can download the zip file whose name starts with single_, which contains sequential single images.
